### ISSUE TITLE
Colorize warning and errors in output

### ISSUE THREAD

**Issue by pierceray** [wellington/wellington#113]
It would be nice if warnings and errors were colorized in the build output.  Hopefully that would pipe through to grunt-wellington as well.

- [x] errors
- [ ] warnings

**Comment by drewwells** [comment]
That can be done. Do you have an example of what color you want. Regular output white... errors red... warnings yellow?

**Comment by pierceray** [comment]
Yup that was what I was thinking. Should the be an "info" color or does that exist in Wellington?

**Comment by drewwells** [comment]
it's really libsass output, wt just forwards it along. Ill need to add some
dependencies for the colorized output

**Comment by drewwells** [comment]
The warnings can be colored but not very useful due to this: https://github.com/sass/node-sass/issues/646

Alternatively, I can disable the warning override and let libsass output its own. Here's an example of the difference

<img width="811" alt="screen shot 2015-08-14 at 10 55 54 pm" src="https://cloud.githubusercontent.com/assets/239123/9287380/79b1f308-42d7-11e5-98af-304736ec45e5.png">

"on line 1 of stdin" would be file:linenumber

**Comment by pierceray** [comment]
The problem I'm trying to highlight is that Bourbon is outputting a lot of WARNINGS for deprecated functionality.  It gets lost in the quantity of output flowing by in a large build.

I like the line number and the yellow warning.  Wish I could have both.

Is this something that the grunt-wellington project could handle rather than having it in wellington proper?

**Comment by drewwells** [comment]
Probably, grunt could try look for `WARNING:` and colorize them. My hands are tied by the lack of parser information provided by libsass. I'm leaning towards letting libsass throw warnings with context (filename/line number) over colorizing output. The warnings are mostly useless without that information (imo).

**Comment by pierceray** [comment]
I would agree, the warnings with context would trump color.
