### ISSUE TITLE
-b doesn't work

### ISSUE THREAD

**Issue by drewwells** [wellington/wellington#181]
fix this

**Comment by wlcx** [comment]
Any workaround/update for this?

**Comment by drewwells** [comment]
hmm good question, I'll take a look to see if it wasn't fixed as a side effect of other changes. Did you notice it was not working?

**Comment by wlcx** [comment]
Yeah, ran `wt watch -p /path/to/sass -b /path/to/css` and it still tries to
use stdin/out


On 23 August 2016 at 17:08:04, Drew Wells (notifications@github.com) wrote:

hmm good question, I'll take a look to see if it wasn't fixed as a side
effect of other changes. Did you notice it was not working?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/wellington/wellington/issues/181#issuecomment-241785792>,
or mute the thread

**Comment by drewwells** [comment]
which version are you using? `wt watch` is correctly reading files to disk and outputting to build directory with latest master.

**Comment by wlcx** [comment]
Ah, 0.9.3. Homebrew must be out of date - mea culpa!

**Comment by drewwells** [comment]
looks like it was fixed in https://github.com/wellington/wellington/commit/4d72c574a

You can check the version by doing `wt -v`
