### ISSUE TITLE
Add OS support to readme

### ISSUE THREAD

**Issue by TheJaredWilcurt** [wellington/wellington#184]
I heard about wellington from this article:

* http://blog.developsuperpowers.com/getting-rid-of-ruby/

Which states it is OSX only. If that is the case, you need to put it in the readme. If that is not the case, you should still put that in the readme to dismiss the rumor.

And to avoid future bothers, you should add the reasoning behind why it only supports one OS (if it does), and what plans you have for making it cross-platform (if it isn't already).

**Comment by drewwells** [comment]
Hmm good point I don't explicitly list OS support. Really happy that people are finding it useful enough to write articles about it!

 Wellington is written for any OS including arm, Solaris, etc but because it uses libsass, we are limited to what  is supported by that library. I'll update the readme to what I'm currently testing which is OS X and Linux. Windows unfortunately stacktraces from libsass when  a sass error is thrown. I chased this for a long time but have finally given up on finding a fix for libsass. Universal OS support is being targeted with a Go native port of the Sass compiler. I am currently deep into this work and hope to bring it online this year. It will speed up wellington and remove many nuances of the C implementation, libsass.

**Comment by TheJaredWilcurt** [comment]
Node-Sass has libsass bindings for each OS. I've been working on a cross-platform desktop app for processing sass, and it's able to handle the error outputs fine in each OS.

* https://github.com/TheJaredWilcurt/scout-app/releases

**Comment by drewwells** [comment]
Yeah it compiles working Sass just fine. However, sass errors segfault
https://github.com/wellington/wellington/issues/160
I've stopped claiming Windows support due to this serious bug.

**Comment by TheJaredWilcurt** [comment]
Maybe I'm misunderstanding what you mean by Sass errors, but if you are talking about stuff where your Sass files are referencing a variable that isn't defined or the syntax is wrong, then that works fine on Windows:

![error](https://cloud.githubusercontent.com/assets/4629794/14764608/f11cc7f8-098b-11e6-80cb-4200681f711c.png)
